print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/mjb462/Desktop/Distortion/UnityProject/Assets/Models/Player/Mesh_Glove_v06@idle_up.mb"`)
{		
	file -o "/Users/mjb462/Desktop/Distortion/UnityProject/Assets/Models/Player/Mesh_Glove_v06@idle_up.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/mjb462/Desktop/Distortion/UnityProject/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/mjb462/Desktop/Distortion/UnityProject/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
