// Unload any plugins before exporting so we don't end up with the wrong version of fbx.
// unloadPlugin `pluginInfo -query -listPlugins`;

// We need to do the plugin loading in another script because
// the plugin needs to be loaded before we execute the script! (Names arent't found otherwise)
if (getApplicationVersionAsFloat() >= 2015.0)
{
	loadPlugin "/Applications/Autodesk/maya2015/Maya.app/../plug-ins/fbx/plug-ins/fbxmaya.bundle";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport.mel\"");
}
else if (getApplicationVersionAsFloat() >= 8.0)
{
	loadPlugin "/Applications/Autodesk/maya2015/Maya.app/Contents/MacOS/plug-ins/fbxmaya.bundle";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport.mel\"");
}
else if (getApplicationVersionAsFloat() >= 7.0)
{
	loadPlugin "/Applications/Autodesk/maya2015/Maya.app/Contents/MacOS/plug-ins/fbxmaya.lib";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport.mel\"");
}
// We need to do the plugin loading in another script because
// the plugin needs to be loaded before we execute the script! (Names arent't found otherwise)
else if (getApplicationVersionAsFloat() >= 6.5)
{
	loadPlugin "/Applications/Unity/Unity.app/Contents/Tools/fbxmaya65.lib";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport.mel\"");
}
else if (getApplicationVersionAsFloat() >= 6.0) 
{
	loadPlugin "/Applications/Unity/Unity.app/Contents/Tools/fbxmaya60.lib";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport.mel\"");
}
else if (getApplicationVersionAsFloat() >= 5.0)
{
	loadPlugin "/Applications/Unity/Unity.app/Contents/Tools/fbxmaya50.lib";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport5.mel\"");
}
else if (getApplicationVersionAsFloat() >= 4.5) 
{
	loadPlugin "/Applications/Unity/Unity.app/Contents/Tools/fbxmaya45.lib";
	eval ("source \"/Users/mjb462/Desktop/Distortion/UnityProject/Temp/FBXMayaExport5.mel\"");
}